config/routes.rb
# This file defines the routes for the Rails application.
# It uses the Rails routing DSL to map URLs to controller actions.

Rails.application.routes.draw do
  devise_for :users

  # Sets the root URL to the "home" action of the "pages" controller.
  root to: "pages#home"

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the routes for the "nodes" resource.
  resources :nodes, only: %i[index create show update destroy] do
    resources :prompts, only: %i[create]
  end

  # Mounts the Sidekiq web interface at "/sidekiq" for admin users.
  # Only users with admin privileges can access this route.
  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end

  # Defines the root path route ("/").
  # This route maps to the "index" action of the "posts" controller.
  # root "posts#index"
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div id="footer" class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    Ce merveilleux site a été réalisé avec <i class="fas fa-heart"></i> par Benjamin, Ludovic et Xavier
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid d-flex">
    <%= link_to "#", class: "navbar-brand" do %>
      <div class= "d-flex justify-content-start">
        <%= image_tag "https://res.cloudinary.com/dk7qaea1j/image/upload/v1710958122/brain-ai-hack/brain_q7isc6.jpg" %>
        <h3 class="ms-3" style="color: white">Brain AI Hack</h3>
      </div>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://res.cloudinary.com/dk7qaea1j/image/upload/v1710958682/brain-ai-hack/XTR9_fyop9z.jpg", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_sidebar.html.erb
<div data-controller="sidebar"
     id="mySidebar"
     class="sidebar"
     data-sidebar-controller-value = <%= controller_name %>
     data-sidebar-action-value = <%= action_name %>
     data-action="mouseover->sidebar#toggleSidebar mouseout->sidebar#toggleSidebar">

  <div class="icondiv sidebare-button <%= current_page?(root_path) ? 'active' : ''%>"  data-action="click->sidebar#changeColor" >
    <%= link_to root_path do %>
      <i class="fa-solid fa-house"></i>Home
    <% end %>
  </div>
  <div class="icondiv sidebare-button <%= !current_page?(controller: "nodes", action: "index") && !current_page?(root_path) ? 'active' : ''%>"  data-action="click->sidebar#changeColor">
    <%= simple_form_for [ node ] do |f|  %>
      <%= f.input :title, as: :hidden %>
      <%= f.simple_fields_for :non_model_field do |nmf| %>
        <%= nmf.input :redirect, as: :hidden, input_html: { value: 'show' } %>
      <% end %>
      <div class="submit" data-sidebar-target="btn">
        <%= button_to type: "submit", class: "button2" do  %>
          <i class="fa-solid fa-terminal"></i>Prompt
        <% end %>
      </div>
    <% end %>
  </div>
  <br>
  <div class="icondiv sidebare-button <%= current_page?(controller: "nodes", action: "index") ? 'active' : ''%>" data-sidebar_target="btn">
    <%= link_to nodes_path, data: {action: "click->sidebar#changeColor"} do %>
      <i class="fa-solid fa-folder"></i>Mes Recherches
    <% end %>
  </div>
</div>